### ISSUE TITLE
Add ability to resolve @scoped/packages subdirectories

### ISSUE THREAD

**Issue by maksimkurb** [leizongmin/vscode-node-module-intellisense#10]
Subdirectories autocompletion for `@scoped/packages` is not working:
![2017-11-01 14-56-53](https://user-images.githubusercontent.com/1351924/32273791-fc429762-bf14-11e7-9516-30e8ddff3ac9.png)

**Comment by leizongmin** [comment]
Hi, I have fixed this problem, please try the newest version v1.5.0
