### ISSUE TITLE
fileModuleExtensions or autoStripExtensions

### ISSUE THREAD

**Issue by DRL9** [leizongmin/vscode-node-module-intellisense#14]
Hello! 
I see a configuration named `node-module-intellisense.fileModuleExtensions` in VSCode Extensions Details. However, I cannot configure it in User Settings. In addition, I find the other named `node-module-intellisense.autoStripExtensions` in github readme.md and this can be configured.

Is the first written wrong?

**Comment by leizongmin** [comment]
I'm so sorry, the `autoStripExtensions` is right. I will correct the document later.
